/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as CreateCategoryImport } from './routes/create-category'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const CreateCategoryRoute = CreateCategoryImport.update({
  id: '/create-category',
  path: '/create-category',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/create-category': {
      id: '/create-category'
      path: '/create-category'
      fullPath: '/create-category'
      preLoaderRoute: typeof CreateCategoryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-category': typeof CreateCategoryRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-category': typeof CreateCategoryRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/create-category': typeof CreateCategoryRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-category'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-category'
  id: '__root__' | '/' | '/create-category'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateCategoryRoute: typeof CreateCategoryRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateCategoryRoute: CreateCategoryRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/create-category"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/create-category": {
      "filePath": "create-category.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
